<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/09 01:55:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=twical',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
