<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/09 01:55:22
sfConfig::add(array(
  'app_sfTwitterAuth_consumer_key' => 'j1f0PAgq23BQpHfqu1I3dA',
  'app_sfTwitterAuth_consumer_secret' => 'ntG04nVidtg5SjEHRcNvjfq6iUfydZIjyD6u9I',
));
