# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
person_modify:
  url:   /person/modify
  param: { module: default, action: personModify }
  
authorised:
  url:   /authorised
  param: { module: default, action: twitterCallback }

twitterLogin:
  url:   /twlogin
  param: { module: sfTwitterAuth, action: login }

login:
  url:   /login
  param: { module: default, action: login }



# default rules
homepage:
  url:   /
  param: { module: default, action: index }
