<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/08 23:42:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=twical',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
